### ISSUE TITLE
Checkout to wrong tag

### ISSUE THREAD

**Issue by dbrulins** [elvanja/jenkins-gitlab-hook-plugin#45]
Hi.

I'm having a problem with builds started by jenkins-gitlab-hook-plugin

Scenario:

gitlab tag push webhook is sent to jenkins instance

Branch Specifier is filled with wildcard expression **[part of tag name]**
when name is matched build start but git repo in workspace checks out to wrong commit

Am I doing something wrong or plugin doesn't support building from tags??

Cheers,
Dominik

**Comment by timroes** [comment]
This doesn't work for me somehow.

I think I've set up everything as you described, as you can see in the following screenshot.

![Config](http://fs2.directupload.net/images/150216/jcm36y5l.png)

Also there is a string parameter with the name BRANCH_TO_BUILD In this task (which just didn't fit onto the screen anymore).

But the job is never triggered when you push a tag. Even thought Gitlab seems to be setup all right, since the tag notification is shown in the logs:

![Logs](http://fs1.directupload.net/images/150216/2uc3zr2j.png)

Any ideas, what could be broken? I tried several combinations of using ${ref} instead, and different branch specifiers, but nothing worked. Triggering plain push does work (without the refspec).

**Comment by javiplx** [comment]
I had a setup similar to yours, and it worked as far as I remember. But I think i didn't prefix with _origin_ on the branch specifier, and anyway I was using my own master branch.
I'm now using another approach, but will take a few weeks to get released. Basically, a TAGNAME variable is available on these cases, and `refs/tags/${TAGNAME}` can be used as branch specifier.

**Comment by timroes** [comment]
I also tried not using `origin/` but unfortunately that didn't help :-(

That other approach sounds very promising. Will there be an update to this jenkins plugin, that will incorporate these changes?

**Comment by javiplx** [comment]
Although this change is not hard, it relies on other changes, so it will but not be soon. Let say probably a bit more than one month.

**Comment by javiplx** [comment]
I believe I've been able to remove dependencies on unreleased parts. You can try with
http://repo.jenkins-ci.org/snapshots/org/jenkins-ci/ruby-plugins/gitlab-hook/1.4.0-SNAPSHOT/
take into account that this will only work if you have a TAGNAME parameter on your job and set the branch specification to `refs/tags/${TAGNAME}`

**Comment by timroes** [comment]
Might I ask, if this bug is fixed in the released 1.4.0 Version?

**Comment by javiplx** [comment]
This is not exactly fixed, but 1.4.0 supports building of tags, using a different approach. Have a look at https://github.com/jenkinsci/gitlab-hook-plugin/#building-tags
