### ISSUE TITLE
build_now hook not working on Jenkins 1.620 and Gitlab 7.8.2

### ISSUE THREAD

**Issue by lehnerchristian** [elvanja/jenkins-gitlab-hook-plugin#61]
Hi,

I set up a Jenkins server and installed this plugin.
Then I set up the build now hook with http://URL_to_server/gitlab/build_now and with the "Push events" option checked.
In Jenkins I didn't configure anything (except the build task), because I didn't see in your docs what I should configure.
The build task is not parameterized and the project is activated.

When I call the hook URL in the browser I get the following, which should be correct when it's called without any payload:

```
repo url could not be found in Gitlab payload or the HTTP parameters:
- body: {}
- parameters: {

}
```

Any ideas what I'm doing wrong?
Thanks in advance!

**Comment by enthusiasmus** [comment]
+1

**Comment by nacsa** [comment]
Hi,

It would be nice if you could provide some log messages, about the hook event. It appears in the Jenkins logs on the webpage. 
The plugin works the following way:
"It will then scan all Git projects in Jenkins and start the build for those that:
- match url of the GitLab repo
- match the configured refspec pattern if any
- and match committed GitLab branch"

So it searches through your projects and look for the matching git repositories used in them. If there is no matching, then no job will build. 

A bug i found in the plugin is that it only works with ssh URL-s, so if you try to connect to git repo with HTTP URL like "http://gitlab-server/Group/Project.git" it won't work, because they only matches the SSL URL.

BTW:
see newer project here: https://github.com/jenkinsci/gitlab-hook-plugin

current issue tracker: http://issues.jenkins-ci.org/secure/IssueNavigator.jspa?mode=hide&reset=true&jqlQuery=project+%3D+JENKINS+AND+status+in+%28Open%2C+%22In+Progress%22%2C+Reopened%29+AND+component+%3D+%27gitlab-plugin%27

**Comment by lehnerchristian** [comment]
Hey @nacsa 

sorry for the late reply. I totally forgot.
We found out that Gitlab never sent a notification to Jenkins.
We already asked the person responsible for the configuration.

But thanks for your help.
